### ISSUE TITLE
有关DiffSinger中文译名的提议 / Suggestions about Chinese translation to "Diffsinger"

### ISSUE THREAD

**Issue by HelimLee** [openvpi/DiffSinger#100]
在过去一段时间内，DiffSinger的用户数量快速上升。作为一个主打面向中文的虚拟歌唱解决方案，一个中文译名可能有其必要。通过这个中文译名，一是能凸显DiffSinger的本地特色，更多的是能扩大其影响力，也提高其作为社区驱动的开源方案的正式程度。相较于基于学术名称的英文名“DiffSinger”，一个理想的中文译名，可以使更广大中文用户对于DiffSinger感到亲切，并进而推进用户社群扩大。典型的成功翻译案例，有如初音未来。典型的中文名称，有如洛天依，都让人感到是高度本地化、成气候的社群氛围。因此我提起此Issue，想对DiffSinger的中文译名做一些提议。个人能力有限，对AI知之甚少，只是想做些外围工作，贡献自己的微薄力量。如有不妥当之处，还需您劳神指出！

In the recent period of time, the number of users of DiffSinger has rapidly increased. As an open-source VSinger solution targeting Chinese audiences, having a Chinese translation may be necessary. Such a translation can not only highlight the local features of DiffSinger, but more importantly, expand its influence and increase its formality as a community-driven open-source solution. Compared to the name based upon academic English name "DiffSinger," an ideal Chinese translation can make more Chinese users feel familiar with DiffSinger, and thus promote the expansion of the user community. Successful cases of translation, such as Hatsune Miku, and typical Chinese names, such as Luo Tianyi, create a highly localized and influential community-driven content creating atmosphere. Therefore, I raise this issue, hoping to propose some Chinese translation for DiffSinger. My personal abilities are limited and my knowledge of AI is scant, but I still want to contribute my humble efforts by doing these non-technical works. If there is any improper wordings or opinions, please feel free to point it out. (This English version is originally created by OpenAI's GPT3 and later modified by myself)

以下是我的若干建议：

Here comes some of my suggestions:

- 根据技术原理：散音 (散音AI)
- 根据技术原理：漫音（漫音AI）
- 根据项目思想：德发声 (Diff音译+人人发声，为每个人提供机会) 
- 根据项目思想：林逾荆（零大于金，代表不收费，同时有志成为商业替代品）
- 综合考量：迭咏 （音译+意译）
- 综合考量：艾楷渊 (AI + 开源（谐音））

**Comment by yjzxkxdn** [comment]
不如地府新歌

**Comment by lujing114514** [comment]
<img width="419" alt="image" src="https://github.com/openvpi/DiffSinger/assets/131372039/1b28a53a-ada6-4804-bbce-3681b2bbaa13">

**Comment by OOPPEENN** [comment]
不如地府新歌

**Comment by lujing114514** [comment]
<img width="475" alt="image" src="https://github.com/openvpi/DiffSinger/assets/131372039/fe8557d8-e028-4af6-b2f9-c821e7e5764b">

**Comment by yjzxkxdn** [comment]
地府歌姬（确信）

**Comment by yqzhishen** [comment]
Anyway, 你有没有发现你举的例子都是歌手名字？而它们的引擎，VOCALOID，以及洛天依 AI 所使用的 ACE Studio，都是没有中文名字的。据我所知目前绝大部分中文 DiffSinger 声库都使用了本地化的中文名称，并且我们在国内进行宣传时也均会使用普通中文母语者容易理解的中文表述指代引擎所涉及的技术要素，不存在所谓不够本地化的问题。

并且我需要纠正你一点，DiffSinger 并不是一个“主打面向中文的虚拟歌唱解决方案”，相反，我们的社区会持续追求全球化、多语种的歌声合成技术和实践。
