### ISSUE TITLE
Make pauses / silence inside singing

### ISSUE THREAD

**Issue by MrDiplodocus** [openvpi/DiffSinger#126]
Hi,
Thank you for the great work! The results are really amazing!
I trained the model and now I have some questions about pauses inside the sample. Is it possible to synthesize a single sample with the silence inside? Adding SP does not help, because the right syllable is concatenated and the model simply sings (lengthens) the syllable, and does not pause it.
![image](https://github.com/openvpi/DiffSinger/assets/8060713/2be5da37-7a46-41fe-8160-b60f434524e8)

**Comment by yqzhishen** [comment]
What editor are you using, and if you use *.ds files to synthesize, how did you get/generate them? Adding `SP`s is expected to work.

**Comment by MrDiplodocus** [comment]
I don't use an editor. I create *.ds files programmatically. I looked in `samples/` and it looks like I found an error with `ph_num`.
I connected `SP` as `AP` according to `3. Add ph_num attribute` from making of variance model. In the `samples/` I saw that `ph_num` for `SP` is equal to `1`.
Thanks for the quick response!
