### ISSUE TITLE
run inference on my own checkpoint

### ISSUE THREAD

**Issue by nestyme** [openvpi/DiffSinger#130]
Hello! Thank you for this wonderful project! 
I've trained my own acoustic model for English singing dataset and now trying to figure out how to run inference on my custom data. I see that I need to create .ds file, but don't understand how to do it correctly. Could you please provide some guidance here? Thank you :)

**Comment by yqzhishen** [comment]
[OpenUtau for DiffSinger](https://github.com/xunmengshe/OpenUtau) is the recommended way to test your models with DS files. You can export your model to ONNX, package it as OpenUtau voicebank, edit music scores, lyrics and parameters in the editor and export *.ds files. There are currently several example DS files in samples/ folder, but those are only for the Chinese dictionary.

**Comment by nestyme** [comment]
@yqzhishen  thank you!

**Comment by yqzhishen** [comment]
@blizzard090 OpenUTAU for DiffSinger has wiki pages for voicebank developers here: https://github.com/xunmengshe/OpenUtau/wiki
