### ISSUE TITLE
能否更改模型保存路径

### ISSUE THREAD

**Issue by SuSWhW** [openvpi/DiffSinger#135]
在colab上有免费的tpu，希望也能够使用tpu训练

**Comment by yqzhishen** [comment]
DiffSinger 使用 Lightning 训练框架，它理论上是支持 TPU 的，可能需要更改 `pl_` 开头的配置项，具体可以查阅官方文档：https://lightning.ai/docs/pytorch/stable/common/trainer.html#trainer-class-api

但是我们没有测试过，如果你有条件测试的话，可以提 PR。

**Comment by SuSWhW** [comment]
> DiffSinger 使用 Lightning 训练框架，它理论上是支持 TPU 的，可能需要更改 `pl_` 开头的配置项，具体可以查阅官方文档：https://lightning.ai/docs/pytorch/stable/common/trainer.html#trainer-class-api
> 
> 但是我们没有测试过，如果你有条件测试的话，可以提 PR。

好的，还有一个问题，就是在训练前，是否能够选择模型的保存路径，colab的运行时在关闭后会释放，我希望能自动同步模型，以免进度消失

**Comment by yqzhishen** [comment]
> 我希望能自动同步模型

设置路径软链接即可。

**Comment by SuSWhW** [comment]
> > 我希望能自动同步模型
> 
> 设置路径软链接即可。

软连接在保存模型的时候会报错，没办法使用软连接

**Comment by yqzhishen** [comment]
那可能是你的系统环境的问题，如果实在无法解决，就考虑修改一下这个地方吧 https://github.com/openvpi/DiffSinger/blob/main/utils/training_utils.py#L264

**Comment by SuSWhW** [comment]
> 那可能是你的系统环境的问题，如果实在无法解决，就考虑修改一下这个地方吧 https://github.com/openvpi/DiffSinger/blob/main/utils/training_utils.py#L264

好的，我目前的方法是将整个diffsinger目录放到colab上挂载的谷歌云盘里
