### ISSUE TITLE
导出的声学模型在openutau中渲染错误

### ISSUE THREAD

**Issue by SuSWhW** [openvpi/DiffSinger#138]
![789bd05c419b8bc25d83774600be80b8](https://github.com/openvpi/DiffSinger/assets/120356642/afe2e692-f1a7-4737-a8f2-afeea09dd7e4)

**Comment by SuSWhW** [comment]
检查过在打包的时候并没有出错

在出现该错误后我尝试了导出锁定gender参数的模型，但依然没有效果

**Comment by yqzhishen** [comment]
这本身应该是一个 OpenUTAU 相关的 issue，但应该是你错误地给没有 gender 输入的 onnx 模型声明了 gender 输入导致的

**Comment by SuSWhW** [comment]
> 这本身应该是一个 OpenUTAU 相关的 issue，但应该是你错误地给没有 gender 输入的 onnx 模型声明了 gender 输入导致的

我并没有给模型声明grander参数，并且全程按照文档操作0.o

**Comment by yqzhishen** [comment]
https://github.com/xunmengshe/OpenUtau/wiki/%E9%9F%B3%E6%BA%90%E5%BC%80%E5%8F%91%E8%80%85%E6%96%87%E6%A1%A3#dsconfigyaml

请看仔细
