### ISSUE TITLE
Error failed to render

### ISSUE THREAD

**Issue by gnloop** [openvpi/DiffSinger#140]
I made a multi singer model with the 2.0 release, but when I try it I get this error:

![1000016595](https://github.com/openvpi/DiffSinger/assets/93042832/ebcbfb8f-f871-4fff-a393-127d9df52f16)

Exporting onnx of the model was also very fast. Did I do something wrong while training? Tensorboard shows training progress normally.

My old multi singer model with the old refactor branch works perfectly fine.

**Comment by yqzhishen** [comment]
This seems to be a voicebank packaging issue that should not belong to this repository. The only changes to the ONNX exporter API in v2.0.0 is the default behavior of exporting speaker embeddings and the ONNX operator set version. Please check if you are using the latest version of OpenUtau and you have written the configuration in the voicebank correctly. You can also use Netron to visualize the ONNX model and see whether the inputs and outputs are the same as the former versions.

**Comment by gnloop** [comment]
It shows up correctly on

**Comment by gnloop** [comment]
Using CPU actually gives a new error that mentions missing breathiness input. Could that be because I set use_breathiness_embed: true but didn't train variance yet?

There's no mention of gender nor breathiness in my dsconfig.yaml, just phonemes, acoustic, vocoder and speakers

**Comment by yqzhishen** [comment]
Ah, that explains everything - OpenUTAU hasn't supported this parameter yet :(

**Comment by gnloop** [comment]
Is it possible to disable it without having to retrain everything?

**Comment by yqzhishen** [comment]
I'm sorry but `breathiness` is a variance parameter, and it has no default values. You have to wait until OpenUTAU supports it.

**Comment by gnloop** [comment]
I see, thank you very much for the help
