### ISSUE TITLE
compatible with master version acoustic pre-train

### ISSUE THREAD

**Issue by nestyme** [openvpi/DiffSinger#141]
Hello! I am trying to find working with latest master pretrain in Releases, but cannot find any. Could you please help me and refer more directly where I can find acoustic pretrain for the latest master version? Thank you

**Comment by yqzhishen** [comment]
Former model releases of MIDI-less mode are still compatible, but they need to be converted to acoustic models before they can be loaded. See release notes of v2.0.0 for migration tips.

**Comment by nestyme** [comment]
thank you!
