### ISSUE TITLE
Melody encoder and ornaments modeling

### ISSUE THREAD

**Issue by yqzhishen** [openvpi/DiffSinger#142]
Melody encoder directly calculates attention on the note sequene besides the linguistic features. With this new method of melody modeling, the pitch predictor gains more sensitiveness on the pitch trend in the music scores, thus imroving accuracy and stability on short slurs, long vibratos and out-of-range notes. In addition, this note-level encoder can also accept ornament tags as input, for example, the glides.

**Comment by yakotoka** [comment]
Is this for the pitch model? Does pitch model training make use of this implementation or this is post pitch model creation? Thank you!

**Comment by yqzhishen** [comment]
@yakotoka This is an improvement to the current pitch model, but models with and without melody encoder will not be compatible with each other.

**Comment by ghhcbef1** [comment]
openutau现在实现这个功能了吗?我试了一下报错了

**Comment by yqzhishen** [comment]
@ghhcbef1 还没有，可能需要等一阵子
