### ISSUE TITLE
onnx exports to incorrect folder

### ISSUE THREAD

**Issue by agentasteriski** [openvpi/DiffSinger#178]
command given: `python scripts/export.py acoustic --exp F:\DiffSinger\ds_training_gui\DiffSinger\checkpoints\AC3\aco --out F:\DiffSinger\ds_training_gui\DiffSinger\checkpoints\AC3\aco\onnx`

the resulting files are instead located in F:\DiffSinger\ds_training_gui\DiffSinger\checkpoints\AC3 with a prefix of **aco.** this pattern repeats with different folder names- the files consistently export to one folder level above the checkpoint with a prefix matching the checkpoint folder. the intended export folder is created if necessary, but otherwise not acknowledged.

**Comment by yqzhishen** [comment]
`--exp` should be the folder name or folder name prefix in your `checkpoints/` directory. Inputting an absolute path as `exp` is an undefined behavior and will cause unexpected results, but when using it the right way it works as expected.
