### ISSUE TITLE
Inference from OpenUTAU USTx -> DiffSinger DS not Carrying Over Parameters

### ISSUE THREAD

**Issue by sillybillylili** [openvpi/DiffSinger#180]
Hi! I'm having issues using .ds files generated through OpenUTAU. Parameters such as speaker, speaker mixing, and tension present don't seem to be carried through when exporting to .ds; only pitch is. I'm not sure if this is a DiffSinger or OpenUTAU issue; however, is there a way to preserve these parameters than exporting from OpenUTAU to DiffSinger?

**Comment by yqzhishen** [comment]
OpenUTAU does not support exporting variance parameters. Actually, it only regards these parameters as intermediate variables and does not persist them at all. You may run inference with your variance checkpoint to obtain the parameters and store them into the ds file, though.
