### ISSUE TITLE
Is removing background noise from audio beneficial to the quality of DiffSinger?

### ISSUE THREAD

**Issue by Alistair-zhong** [openvpi/DiffSinger#190]
Thank you very much to the OpenVPI team for maintaining the open-source DiffSinger branch.

I want to train a DiffSinger Model, and wanna know Is removing background noise from audio beneficial to the quality of DiffSinger?

<img width="806" alt="image" src="https://github.com/openvpi/DiffSinger/assets/58490734/226efa91-9a1d-45c1-8f69-c6b0e315d0f3">

Thanks~

**Comment by yqzhishen** [comment]
The noise shown in your screenshot does not seem severe. You can just crop the silence segments.

**Comment by blueyred** [comment]
@Alistair-zhong depends on how prominent the noise is, say you have some classic microphone hum at a constant 180 or 300Hz - your singing model will learn it and it will be present in your generations. If its something thats very occasional you may find it gets buried by your other recording data. Generally though the audio you put in you get out.
