### ISSUE TITLE
Error training variance model

### ISSUE THREAD

**Issue by Surya-29** [openvpi/DiffSinger#199]
I'm getting this error during the start of variance model training. I also tried changing the configuration parameters (all pl configs and also tried setting nccl_p2p : `false` ) but yet the error keeps popping up.

`Epoch 0:   0%|                                           | 0/30 [00:00<?, ?it/s]terminate called after throwing an instance of 'std::runtime_error'
  what():  torch_xla/csrc/runtime/runtime.cc:23 : $PJRT_DEVICE is not set.`

**Comment by KakaruHayate** [comment]
torch_xla...
You are running on TPU?

**Comment by Surya-29** [comment]
Nope, I'm running it on a GCP VM and the compute engine is T4 GPU

**Comment by tideka** [comment]
Are you running GCP VM with Google Colab Notebook? I have seen Colab adding preinstalled (and mismatch) dependency. Maybe you have to try on a "fresh" system, with the maintainer provided requirements installed.
