### ISSUE TITLE
hnsep refers to the vocoder?

### ISSUE THREAD

**Issue by MikeMpapa** [openvpi/DiffSinger#210]
Hi, 
I wonder if checkpoint/vr refers to the vocoder and its config.yaml file?

If yes, I wonder if there are pretrained vocoder weights and config.yaml that I  can use to train my custom variance/Diffsinger?

All the vocoders I found looking in the repo are not compatible with the DiffSinger(openvpi) format. and I keep getting the following error

`RuntimeError: Error(s) in loading state_dict for CascadedNet:
        Missing key(s) in state_dict:  ListOfMissingKeys`

**Comment by yqzhishen** [comment]
hnsep is the harmonic-noise separation model. See https://github.com/openvpi/DiffSinger/blob/main/docs/BestPractices.md
