### ISSUE TITLE
关于训练数据的准备

### ISSUE THREAD

**Issue by koalaaaaaaaaa** [openvpi/DiffSinger#27]
请问数据在训练前要如何准备呢（想训练具有某人音色的歌姬的话），可否出一些教程呢？万分感谢！
都是国人就不用英文了[doge]

**Comment by yqzhishen** [comment]
教程和相关的自动化流程正在 no-midi 分支的 pipelines 目录下进行准备，请留意我们的通知。

**Comment by yqzhishen** [comment]
数据集的制作见 pipelines/no_midi_preparation.ipynb。
中文教程：https://www.yuque.com/sunsa-i3ayc/sivu7h/atqv1388lt5au0yz
