### ISSUE TITLE
切片时，两段歌声之间会留存超长的无声片段

### ISSUE THREAD

**Issue by ZJ-CAI** [openvpi/DiffSinger#36]
比如切片结果里，有一段15秒的切片，0~4秒是有歌声的，4~11秒是静音，然后11~15秒又是有歌声的，请问slicer中的参数该如何修改，能让切片更精准。

目前参数：
db_threshold_ = -7.5, min_length_ = 5000, win_l_ = 400, win_s_ = 20, max_silence_kept_ = 100

**Comment by yqzhishen** [comment]
你的代码是过时的，请更新
```bash
git pull
```
