### ISSUE TITLE
关于python环境变量的问题

### ISSUE THREAD

**Issue by SuSWhW** [openvpi/DiffSinger#41]
我在预处理那一步cd到仓库目录输入了PYTHONPATH这个环境变量，然后我发现标注有问题，修正后想重新整一遍数据集，然后发现无法用笔记本导入模块。请问怎么解决
```bash
No module named 'utils.distribution'
```

**Comment by yqzhishen** [comment]
重新开个终端试一下呢

**Comment by SuSWhW** [comment]
我在这个步骤用的是ipynb，不是终端
报错的地方在步骤3.1，在更改PYTHONPATH之前一切正常

**Comment by SuSWhW** [comment]
我实在不行重装一下python

**Comment by yqzhishen** [comment]
重开一个终端启动jupyter notebook试过吗？

**Comment by SuSWhW** [comment]
试过，还是这样

**Comment by yqzhishen** [comment]
重启，还不能解决就暂时把PYTHONPATH设成pipelines/

**Comment by SuSWhW** [comment]
好的

**Comment by SuSWhW** [comment]
试过了，还是报错没有模块

**Comment by SuSWhW** [comment]
我先重装python逝逝
