### ISSUE TITLE
数据集制作3.2 cell 2

### ISSUE THREAD

**Issue by QFDG** [openvpi/DiffSinger#44]
![QQ截图20230205180142](https://user-images.githubusercontent.com/108403140/216825930-4eb72c02-f20b-43b7-9632-c1584cf19605.png)
把beam后的数字调大，从100试到了10000还是报错
log导出能找到出错音频文件名字，改完后重试 每次导出的log的文件名都不一样

**Comment by yqzhishen** [comment]
请你检查是否是在 Windows 下制作数据集，系统编码为 GBK，并且文件名带有中文。
另外，非必要请勿调大 beam，否则可能导致准度下降。

**Comment by QFDG** [comment]
au响度匹配的时候导出文件自动带了中文名，当时没注意QAQ
