### ISSUE TITLE
AttributeError: 'DiffSingerE2EInfer' object has no attribute 'spk_map'

### ISSUE THREAD

**Issue by MarcoBay** [openvpi/DiffSinger#47]
file base_svs_infer.py. Class BaseSVSInfer has no spk_map singletone if use_spk_id is false.

it cause me a error on d2_e2e.py

**Comment by yqzhishen** [comment]
Okay, this will be fixed in a moment.
But please do not use DiffSingerE2eInfer anymore, since this mode has been deprecated in this fork and no further updates will be provided.
