### ISSUE TITLE
你好, pipelines/asserts/*.lab 文件格式是什么样的

### ISSUE THREAD

**Issue by DuQingChen** [openvpi/DiffSinger#50]
歌词中的标点符号怎么处理

**Comment by DuQingChen** [comment]
明白了,可以忽略标点

**Comment by DuQingChen** [comment]
明白了,标点符号可以忽略.不知道能不能使用 [AP], [SP] 代替标点符号

**Comment by flutydeer** [comment]
不需要手动标注 AP 和 SP。关于数据集制作，请阅读教程 https://www.yuque.com/sunsa-i3ayc/sivu7h
