### ISSUE TITLE
mfa无法对齐音素

### ISSUE THREAD

**Issue by SuSWhW** [openvpi/DiffSinger#52]
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data[ in a text editor](command:workbench.action.openLargeOutput?fcd4dbbd-6da5-471b-bb91-e7e8bec5d3c3)
Pretrained model already exists.

Run the following command in your terminal manually if it fails here:
mfa align pipelines/segments dictionaries/opencpop-extension.txt pipelines/assets/mfa-opencpop-extension.zip pipelines/textgrids --beam 100 --clean --overwrite
INFO - Setting up corpus information...
INFO - Loading corpus from source files...
INFO - Found 1 speaker across 164 files, average number of utterances per speaker: 164.0
INFO - Initializing multiprocessing jobs...
WARNING - Number of jobs was specified as 3, but due to only having 1 speakers, MFA will only use 1 jobs.
INFO - Creating corpus split for feature generation...
INFO - Generating base features (mfcc)...
INFO - Generating MFCCs...
MultiprocessingError:

  Job 0 encountered an error:
  Traceback (most recent call last):

    File "D:\Miniconda3\envs\diff\lib\site-packages\montreal_forced_aligner\abc.py", line 73, in run
      yield from self._run()

    File "D:\Miniconda3\envs\diff\lib\site-packages\montreal_forced_aligner\corpus\features.py", line 251, in _run
      self.check_call(copy_proc)

    File "D:\Miniconda3\envs\diff\lib\site-packages\montreal_forced_aligner\abc.py", line 100, in check_call
      raise KaldiProcessingError([self.log_path])
...
    There were 1 job(s) with errors when running Kaldi binaries.
    See the log files below for more information.
    C:\Users\Q78KGa/Documents/MFA\segments_pretrained_aligner\segments\split1\log\make_mfcc.0.log
ERROR - There was an error in the run, please see the log.

  0%|          | 0/100 [00:00<?, ?it/s]
  1%|          | 1/164 [00:01<05:09,  1.90s/it]
 26%|██▌       | 42/164 [00:02<00:04, 29.14it/s]
 62%|██████▏   | 101/164 [00:02<00:00, 80.00it/s]
 95%|█████████▌| 156/164 [00:02<00:00, 133.50it/s]
100%|██████████| 164/164 [00:03<00:00, 50.26it/s] 

  0%|          | 0/164 [00:00<?, ?it/s]
  0%|          | 0/164 [00:02<?, ?it/s]

**Comment by yqzhishen** [comment]
提 issue 前请先搜索有没有已解决的相同问题：https://github.com/openvpi/DiffSinger/issues/44

**Comment by SuSWhW** [comment]
好的
