### ISSUE TITLE
教程链接失效了

### ISSUE THREAD

**Issue by umq34p99a3v8uqrpq984t** [openvpi/DiffSinger#69]
[中文教程](https://www.yuque.com/sunsa-i3ayc/sivu7h)

**Comment by flutydeer** [comment]
感谢你的反馈，我们已经注意到此情况，正在处理。在问题解决前，可以先尝试阅读 README 和观看 B 站上的教程视频来使用。

**Comment by Minidoracat** [comment]
demo 也都失效了

**Comment by yqzhishen** [comment]
> demo 也都失效了

demo哪儿失效了？
