### ISSUE TITLE
使用ddps

### ISSUE THREAD

**Issue by detectiveli** [openvpi/DiffSinger#71]
您好啊~

我根据这个ddps生成了jit文件，但是调用的时候报错：

![image](https://user-images.githubusercontent.com/25707963/226528527-ff90c12d-98bc-4ece-82a2-fdd341298326.png)

感觉是jit文件没有保存好。保存的时候我使用的是pytorch 1.8.2(同本程序的教程)

期待您的回复

**Comment by yxlllc** [comment]
可能是低版本torch jit不支持复数张量

**Comment by yqzhishen** [comment]
首先纠正一下，是ddsp不是ddps。
如果你的ddsp的mel参数和音频采样率和你此前训练的声学模型完全一致的话，声学模型是不需要重新训练的。

**Comment by detectiveli** [comment]
> 首先纠正一下，是ddsp不是ddps。 如果你的ddsp的mel参数和音频采样率和你此前训练的声学模型完全一致的话，声学模型是不需要重新训练的。

哈 ddsp,不好意思了。

其实我本来是想训练原始diffsinger的vocoder来提升声音质量（看起来原版是NsfHifiGAN）。不过在他的issues里面发现他说这部分卖给公司了。我刚参照本程序训练了一份ddsp（44100hz），也可以做驱动。但是他应该是需要ph级别的label，我试一下ddsp可不可以放回原来的程序里做word级别的预测。

非常感谢！
