### ISSUE TITLE
MFA training

### ISSUE THREAD

**Issue by yqzhishen** [openvpi/DiffSinger#8]

**Comment by AlexandaJerry** [comment]
OOV tokens and types has been decreased to 0.
I'm starting to train the acoustic model based on Opencpop dataset.
An instruction for wheels on textgrid-split and textgrid-to-txt is on the way.
Guidance on running MFA through Google Colab is on the way.

**Comment by yqzhishen** [comment]
> OOV tokens and types has been decreased to 0. I'm starting to train the acoustic model based on Opencpop dataset. An instruction for wheels on textgrid-split and textgrid-to-txt is on the way. Guidance on running MFA through Google Colab is on the way.

Feel free to make another repository to hold the training code if you think it's necessary. The structure of this repository is kind of chaotic. 😂
