### ISSUE TITLE
Docs for tts/

### ISSUE THREAD

**Issue by d4n1elchen** [openvpi/DiffSinger#82]
Is there a doc for tts tasks? or could you give me some hint about how to run it. Thanks.

**Comment by RigoLigoRLC** [comment]
This fork is focused on SVS and TTS functionality in this fork is entirely unmaintained and untested. No documentation is planned and you probably should use MoonInTheRiver's original repo for TTS instead too.

**Comment by flutydeer** [comment]
Since tts is deprecated in this fork, please visit the upstream repository.
[https://github.com/MoonInTheRiver/DiffSinger](https://github.com/MoonInTheRiver/DiffSinger)
