### ISSUE TITLE
i wanna use "forced automatic pitch modem" without F0 truth

### ISSUE THREAD

**Issue by lvZic** [openvpi/DiffSinger#92]
however, following crashed

https://github.com/openvpi/DiffSinger/blob/d9f66c7961a4ee82049c24a99499a4f1966fc1e7/inference/ds_cascade.py#L267

  File "openvpi/DiffSinger/modules/naive_frontend/encoder.py", line 72, in forward
    delta_l = nframes - f0.size(1)
AttributeError: 'NoneType' object has no attribute 'size'

seems it stiil use input f0 as model param.

**Comment by lvZic** [comment]
> This mode is not suggested because in the current default branch, most models cannot predict f0 themselves, and models which have f0 predictors outputs poor f0. I don't think you will really need to run a model without f0 truth.
> 
> F0 predictors are totally removed in refactor-v2 branch, and are re-implemented with more advanced architecture and algorithm in variance branch.

So i should use variance branch to inference without F0 truth?
In fact, i hane tried the author's official version, and the preformance seems not sota.

**Comment by lvZic** [comment]
> This mode is not suggested because in the current default branch, most models cannot predict f0 themselves, and models which have f0 predictors outputs poor f0. I don't think you will really need to run a model without f0 truth.
> 
> F0 predictors are totally removed in refactor-v2 branch, and are re-implemented with more advanced architecture and algorithm in variance branch.

I wanna know how the ds_variance.py file get the final wav file by  returned dur_pred, f0_pred, variance_pred ?

**Comment by yqzhishen** [comment]
Non-default branches are not suitable for any user who does not have much coding skills and knowledge about this project. Please wait for the formal release in June.
