### ISSUE TITLE
question about MIDI and F0

### ISSUE THREAD

**Issue by lvZic** [openvpi/DiffSinger#96]
1. I wonder how to get F0 truth in practice ? In my opinion, MIDI could be labeled mannually,  and  the F0 truth are usually got from human voice? And i wonder why you focus on midiless version in future, the midiless performance better than midi one or the midi lable is harder to obtain than F0?
2. In my test, the ph_dur estimation is poor, when test  your midi-A version. If given the ph_dur GT as input, the performance is improved a lot. However  the performance in midi-B test is always  better than midi-A test .
 I am new to SVS, sorry for above questions.

**Comment by yqzhishen** [comment]
1. Advantages of doing so are discussed in #67. MIDI are harder to label, and decoupling MIDI from acoustic models can improve the controllability and performance. In the future, pitch (f0) can be predicted from lyrics and MIDI via variance models.
2. Old MIDI-A and MIDI-B both have duration predictors; there is no difference in their duration prediction method and logic.

**Comment by yqzhishen** [comment]
0831 is a really old checkpoint. At that time we haven't gone far from the original repo.
